// GENERATED by scripts/sync_brand.ts from the BRAND CONFIG block in CLAUDE.md.
// Do not edit by hand. Run: npm run brand:sync

export const brand = {
  name: "Glowy Homes",
  short: "GH",
  domain: "glowy.homes",
  tagline: "Find your place.",
  market: {
    country: "CA",
    region: "Ontario",
    cities: [{"name":"Toronto","slug":"toronto"},{"name":"Mississauga","slug":"mississauga"},{"name":"Ottawa","slug":"ottawa"},{"name":"Hamilton","slug":"hamilton"},{"name":"London","slug":"london"}],
  },
  currency: "CAD",
  units: "metric",
  listingFeed: "synthetic",
  color: "#1D4ED8",
  colorHover: "#1A46C2",
  neutralScale: "slate",
  fontSans: "Jost",
  fontDisplay: "Bodoni Moda",
  supportEmail: "support@glowy.homes",
} as const;

export type Brand = typeof brand;
