// GENERATED by scripts/sync_brand.ts from the BRAND CONFIG block in CLAUDE.md.
// Do not edit by hand. Run: npm run brand:sync

export const brand = {
  name: "GlowHomes",
  short: "GH",
  domain: "glowy.homes",
  tagline: "Find your place.",
  market: {
    country: "US",
    region: "California",
    cities: [{"name":"Los Angeles","slug":"los-angeles"},{"name":"San Diego","slug":"san-diego"},{"name":"San Jose","slug":"san-jose"},{"name":"San Francisco","slug":"san-francisco"},{"name":"Sacramento","slug":"sacramento"}],
  },
  currency: "USD",
  units: "imperial",
  listingFeed: "synthetic",
  color: "#1D4ED8",
  colorHover: "#1A46C2",
  neutralScale: "slate",
  fontSans: "Jost",
  fontDisplay: "Bodoni Moda",
  supportEmail: "support@glowy.homes",
} as const;

export type Brand = typeof brand;
