import { z } from "zod";
import { slugify } from "../../src/lib/slug";

export const BrandConfig = z.object({
  brand_name: z.string().min(1),
  brand_short: z.string().min(2).max(3),
  domain: z.string().min(3),
  tagline: z.string().min(1),
  primary_market_country: z.enum(["CA", "US"]),
  primary_market_region: z.string().min(1),
  primary_market_cities: z.array(z.string().min(1)).min(1),
  currency: z.string().length(3),
  units: z.enum(["metric", "imperial"]),
  listing_feed: z.enum(["synthetic", "reso_web_api", "crea_ddf", "csv"]),
  brand_color: z.string().regex(/^#[0-9A-Fa-f]{6}$/),
  neutral_scale: z.enum(["zinc", "slate", "gray", "neutral", "stone"]),
  font_sans: z.string().min(1),
  support_email: z.string().email(),
});
export type BrandConfig = z.infer<typeof BrandConfig>;

/** Extracts the yaml block under "BRAND CONFIG" in CLAUDE.md and parses the flat key: value lines. */
export function parseBrandBlock(markdown: string): BrandConfig {
  const section = markdown.split(/^## \d+\. BRAND CONFIG.*$/m)[1];
  if (!section) throw new Error("BRAND CONFIG section not found in CLAUDE.md");
  const block = section.match(/```yaml\r?\n([\s\S]*?)```/);
  if (!block) throw new Error("BRAND CONFIG yaml block not found");

  const raw: Record<string, unknown> = {};
  for (const line of block[1].split(/\r?\n/)) {
    // A value is a quoted string, a JSON array, or a bare token; anything after it is a comment.
    const m = line.match(/^(\w+):\s*("[^"]*"|\[[^\]]*\]|[^\s#]+)/);
    if (!m) continue;
    const [, key, value] = m;
    raw[key] = value.startsWith("[") ? JSON.parse(value) : value.replace(/^"(.*)"$/, "$1");
  }
  return BrandConfig.parse(raw);
}

/** Darkens a hex color by mixing it toward black. amount 0.1 = 10%. */
export function shade(hex: string, amount: number): string {
  const n = parseInt(hex.slice(1), 16);
  const channel = (shift: number) =>
    Math.round(((n >> shift) & 0xff) * (1 - amount))
      .toString(16)
      .padStart(2, "0");
  return `#${channel(16)}${channel(8)}${channel(0)}`.toUpperCase();
}

export { slugify };

export function renderBrandTs(cfg: BrandConfig): string {
  const cities = cfg.primary_market_cities.map((name) => ({ name, slug: slugify(name) }));
  return `// GENERATED by scripts/sync_brand.ts from the BRAND CONFIG block in CLAUDE.md.
// Do not edit by hand. Run: npm run brand:sync

export const brand = {
  name: ${JSON.stringify(cfg.brand_name)},
  short: ${JSON.stringify(cfg.brand_short)},
  domain: ${JSON.stringify(cfg.domain)},
  tagline: ${JSON.stringify(cfg.tagline)},
  market: {
    country: ${JSON.stringify(cfg.primary_market_country)},
    region: ${JSON.stringify(cfg.primary_market_region)},
    cities: ${JSON.stringify(cities)},
  },
  currency: ${JSON.stringify(cfg.currency)},
  units: ${JSON.stringify(cfg.units)},
  listingFeed: ${JSON.stringify(cfg.listing_feed)},
  color: ${JSON.stringify(cfg.brand_color)},
  colorHover: ${JSON.stringify(shade(cfg.brand_color, 0.1))},
  neutralScale: ${JSON.stringify(cfg.neutral_scale)},
  fontSans: ${JSON.stringify(cfg.font_sans)},
  supportEmail: ${JSON.stringify(cfg.support_email)},
} as const;

export type Brand = typeof brand;
`;
}

/**
 * Maps the configured neutral family onto `neutral-*` utilities. Values are copied from
 * Tailwind's theme.css because Tailwind drops unused theme variables, so var() references
 * to the source family would not resolve.
 */
export function renderBrandCss(cfg: BrandConfig, tailwindThemeCss: string): string {
  const steps = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
  const neutral = steps
    .map((s) => {
      const m = tailwindThemeCss.match(new RegExp(`--color-${cfg.neutral_scale}-${s}:\\s*([^;]+);`));
      if (!m) throw new Error(`Tailwind color ${cfg.neutral_scale}-${s} not found`);
      return `  --color-neutral-${s}: ${m[1]};`;
    })
    .join("\n");
  return `/* GENERATED by scripts/sync_brand.ts from CLAUDE.md. Do not edit by hand. */
@theme {
  --color-accent: ${cfg.brand_color};
  --color-accent-hover: ${shade(cfg.brand_color, 0.1)};
${neutral}
}
`;
}
